### ISSUE TITLE
A thank you "issue"

### ISSUE THREAD

**Issue by jwr** [bigmlcom/sketchy#13]
This isn't really an "issue", I just wanted to use the issues mechanism to thank you for making this library available. It is very useful, especially given its small size and amazingly simple implementations (it is clear you've done some creative thinking to come up with these, I've spent some time reading the code to understand it and make sure it is valid, and I am impressed).

Thanks again!

**Comment by ashenfad** [comment]
This is my favorite type of 'issue'. Thanks for the kind words, @jwr!

I'm glad the library is useful for you. I was certainly a good exercise for me when I built it.
