### ISSUE TITLE
sketchy incompatible with hadoop because of guava depenency

### ISSUE THREAD

**Issue by dribnet** [bigmlcom/sketchy#5]
Hi - just wanted to let you know that I considered using this awesome looking library for a project, but had to abort because of a hadoop / guava incompatibility. This is a well known problem that you can find refrences to [all](https://github.com/paulhoule/infovore/wiki/Hadoop-And-Guava) / [over](http://stackoverflow.com/questions/23909588/nosuchmethoderror-using-guava-15-on-hadoop-2-3-0) / [the](https://issues.apache.org/jira/browse/HADOOP-10101) / [interwebs](https://groups.google.com/a/cloudera.org/forum/#!msg/cdh-user/d5_HqUSvVl4/KLLdgHsjkUcJ).

Maven has a solution for this called [relocating classes](http://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) (via the [maven shade plugin](http://maven.apache.org/plugins/maven-shade-plugin/source-repository.html)) which nicely takes care of this problem. Leiningen has support for maven-shade functionality in :uberjar-merge-with which is covered well in technomancy/leiningen#973, but for whatever reason doesn't seem to support relocation.

Just wanted to share this in case anyone else has the same issue. Since for now I just needed a HyperLogLog, I'm going to instead grab AddThis' stream-lib [HyperLogLog.java](https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/cardinality/HyperLogLog.java), but hope to come back to sketchy in the future if I can figure out how to shadow guava's siphashing classes.

**Comment by ashenfad** [comment]
Thanks for the heads up.  I might drop Guava (and SipHash) as a dependency in the next version and use a seedable 64-bit Murmur hash instead.  Feel free to try it out on my [murmur branch](https://github.com/ashenfad/sketchy/tree/murmur).

**Comment by dribnet** [comment]
Super! I looked at your branch and it looked good. One thing though - I probably wouldn't stick the whole murmurhash implementation in there, and even then I might not include that particular version of murmurhash. As some respectable internet citizen pointed out a year or so ago in tnm/murmurhash-java#3, it seems that one might not be compatible with other implementations.

I've had great luck with @ztellman's [byte-transforms library](https://github.com/ztellman/byte-transforms). After dropping `[byte-transforms "0.1.3"]` in your dependencies, you should be able to do something like
```clj
(:require [byte-transforms :as bt])
(def hash (bt/hash my-string :murmur128))
```

**Comment by ashenfad** [comment]
Ha!  Small world.  I hadn't seen `byte-transforms`, so thanks for the tip.

Its Clojure api is sadly a bit slow (and no automatic type->bytes coercion), but its `CassandraMurmurHash` is nearly a drop in [replacement](https://github.com/ashenfad/sketchy/commit/b33462e72101f2c60183ea628c7c406d8fcd5ccc).

**Comment by ztellman** [comment]
Out of curiosity, what makes you say it's slow?

**Comment by ashenfad** [comment]
I threw together a stupid little test that compared my [original hash fn](https://github.com/ashenfad/sketchy/blob/murmur/src/clj/bigml/sketchy/murmur.clj#L27) and a candidate replacement which called `byte-transforms/hash`. My original function [retreats to Java](https://github.com/ashenfad/sketchy/blob/murmur/src/java/bigml/sketchy/MurmurUtil.java) for ByteBuffer coercion and calling `CassandraMurmurHash`.

```clojure
(defn hash
  "Returns a long hash given a value and an optional seed."
  ([val]
   (hash* val default-seed))
  ([val seed]
   (hash* val (seed->long seed))))

(defn hash-bt
  "Returns a long hash given a value and an optional seed."
  ([val]
   (bt/hash val :murmur64))
  ([val seed]
   (bt/hash val :murmur64 {:seed (seed->long seed)})))
```

There's a little extra overhead for the `hash-bt` calls:

```clojure
(def dumb-strings (vec (repeat 1000000 "abcde")))

(time (doseq [s dumb-strings] (murmur/hash s)))
;; "Elapsed time: 752.238 msecs"

(time (doseq [s dumb-strings] (murmur/hash-bt s)))
;; "Elapsed time: 1181.003 msecs"
```

**Comment by ztellman** [comment]
If I use Criterium to do the benchmarking on my 3 year old laptop, the results are inverted:

```clj
bigml.sketchy.murmur> (require '[criterium.core :as c])
nil
bigml.sketchy.murmur> (require '[byte-transforms :as bt])
nil
bigml.sketchy.murmur> (c/quick-bench (hash "abcde"))
WARNING: Final GC required 1.7087883402915571 % of runtime
WARNING: Final GC required 14.489135893531849 % of runtime
Evaluation count : 5557542 in 6 samples of 926257 calls.
             Execution time mean : 104.011251 ns
    Execution time std-deviation : 2.424386 ns
   Execution time lower quantile : 101.902225 ns ( 2.5%)
   Execution time upper quantile : 107.140512 ns (97.5%)
                   Overhead used : 1.959879 ns
nil
bigml.sketchy.murmur> (c/quick-bench (bt/hash "abcde" :murmur64))
WARNING: Final GC required 13.24873663119806 % of runtime
Evaluation count : 7243110 in 6 samples of 1207185 calls.
             Execution time mean : 85.042390 ns
    Execution time std-deviation : 2.806434 ns
   Execution time lower quantile : 81.327273 ns ( 2.5%)
   Execution time upper quantile : 88.284574 ns (97.5%)
                   Overhead used : 1.959879 ns
```

Note that I added `:jvm-opts ^:replace ["-server"]` to the project.clj, which is crucial whenever you're doing any sort of benchmarking.  There's a tiny bit more indirection in byte-transforms, but but server-mode JVM, given time to JIT, will take care of that.

**Comment by ashenfad** [comment]
Ah, you're right.  The JVM server option makes all the difference.

**Comment by dribnet** [comment]
Hi Adam - your murmur branch seems to be working well in my limited testing. If you think you'll be moving forward without Guava, how about you go ahead and push a 0.3.0 SNAPSHOT to maven with that change, and I'll verify things are working downstream.
