### ISSUE TITLE
Min-hash constrained by Integer/MAX_VALUE

### ISSUE THREAD

**Issue by gramji** [bigmlcom/sketchy#8]
Hi guys,

When computing min-hashes, for many inputs, the signature component defaults to Integer/MAX_VALUE because the input hashes (generated by 64bit murmur hash) are all larger that Integer/MAX_VALUE.

Have you faced this issue before or is it just me?!

Thanks
Gireesh

**Comment by ashenfad** [comment]
Good catch - thanks!  The initial value should have been `Long/MAX_VALUE`.

Even with the bug there was about a 50% chance that a hash would be smaller than `Integer/MAX_VALUE` each time a new item was added.  So min-hashes built on anything other than very small datasets should have been fine.

Nonetheless, it's fixed as of 0a98204 (version 0.3.1).
